name: Terraform CI

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'tests/**'

jobs:
  terratest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'

    - name: Run Terratest
      run: |
        cd tests
        go test -v
